---
config:
  layout: dagre
  elk:
    mergeEdges: true
    nodePlacementStrategy: LINEAR_SEGMENTS
  look: classic
---
classDiagram
direction TB

	namespace Finanzdokumente {
        class Rechnung {
	        -rechnungsnummer: Ganzzahl
	        -betrag: Dezimalzahl
	        -fälligkeitsdatum: Datum
	        -status: Text
        }

	}
    namespace Mitarbeiter_und_Gruppen {
        class Person {
	        -vorname: Text
	        -nachname: Text
	        -telefon: Text
	        -email: Text
        }

        class Mitarbeiter {
	        -mitarbeiternummer: Ganzzahl
	        -geburtsdatum: Datum
	        -position: Text
	        -beschäftigungsart: Text
	        -vertragsbeginn: Datum
	        -vertragsende: Datum
        }

        class Adresse {
	        -straße: Text
	        -hausnummer: Text
	        -plz: Text
	        -ort: Text
	        -land: Text
        }

        class Rolle {
	        -rollennummer: Ganzzahl
	        -name: Text
        }

        class Gruppe {
	        -gruppennummer: Ganzzahl
	        -gruppenname: Text
	        -gruppentyp: Text
	        -beschreibung: Text
        }

        class Anwesenheitszeit {
	        -anwesenheitsID: Ganzzahl
	        -datum: Datum
	        -startzeit: Zeit
	        -endzeit: Zeit
	        -typ: Text
	        -bemerkung: Text
        }

	}
	
    namespace `Projekte_und_Aufträge` {
        class Projekt {
	        -projektnummer: Ganzzahl
	        -projektname: Text
	        -starttermin: Datum
	        -endtermin: Datum
	        -beschreibung: Text
	        -status: Text
        }

        class Arbeitsauftrag {
	        -auftragsnummer: Ganzzahl
	        -auftragsbezeichnung: Text
	        -bauplan: Text
	        -starttermin: Datum
	        -endtermin: Datum
	        -kostenvoranschlag: Dezimalzahl
	        -status: Text
	        -bemerkung: Text
        }

        class Unterauftrag {
	        -unterauftragsnummer: Ganzzahl
	        -bezeichnung: Text
	        -starttermin: Datum
	        -endtermin: Datum
	        -status: Text
	        -kosten: Dezimalzahl
	        -bemerkung: Text
        }

        class Unterauftragnehmer {
	        -unterauftragnehmerID: Ganzzahl
	        -firmenname: Text
	        -fachbereich: Text
        }

        class Termin {
	        -terminID: Ganzzahl
	        -datum: Datum
	        -uhrzeit: Zeit
	        -bezeichnung: Text
	        -beschreibung: Text
        }

	}
	

	namespace `Geräte_und_Ausrüstung` {
        class `GerätTyp` {
	        -geräteTypID: Ganzzahl
	        -bezeichnung: Text
	        -typ: Text
	        -kategorie: Text
        }

        class `GerätExemplar` {
	        -gerätenummer: Ganzzahl
	        -seriennummer: Text
	        -standort: Text
	        -status: Text
	        -anschaffungsdatum: Datum
	        -letzterWartungstermin: Datum
	        -nächsterWartungstermin: Datum
        }

        class `Ausrüstung` {
	        -ausrüstungsnummer: Ganzzahl
	        -bezeichnung: Text
	        -typ: Text
	        -kompatibelMit: Text
	        -gewicht: Dezimalzahl
	        -status: Text
        }

        class Lager {
	        -lagernummer: Ganzzahl
	        -lagerbezeichnung: Text
	        -typ: Text
	        -grundstück: Text
	        -kapazität: Ganzzahl
        }

	}
	namespace Buchungen {
        class Buchung {
	        -buchungsnummer: Ganzzahl
	        -startdatum: Datum
	        -enddatum: Datum
	        -buchungsdatum: Datum
	        -status: Text
        }

	}
	namespace Bilder {
        class Bild {
	        -bildID: Ganzzahl
	        -titel: Text
	        -dateipfad: Text
	        -dateiname: Text
	        -elementtyp: Text
	        -hochladedatum: Datum
	        -dateigröße: Ganzzahl
	        -format: Text
        }

	}
	namespace Externe_Systeme {
        class Finanzbuchhaltung {
	        +leseRechnungen()
	        +leseMahnungen()
	        +leseKostenvoranschläge()
        }

        class Altsystem {
	        +importiereDaten()
        }

        class Drucker {
	        +drucke(dokument)
        }

	}
    

	<<extern>> Finanzbuchhaltung
	<<extern>> Altsystem
	<<extern>> Drucker

    Mitarbeiter --|> Person
    Person "0..*" --> "1" Adresse : adresse
    Mitarbeiter "0..*" --> "1" Rolle : rolle
    Mitarbeiter "0..*" -- "0..*" Gruppe : gruppen
    Gruppe "0..*" --> "0..1" Mitarbeiter : gruppenleiter
    Mitarbeiter "1" *-- "0..*" Anwesenheitszeit : anwesenheitszeiten
    Unterauftragnehmer --|> Person
    Projekt "0..*" --> "1" Mitarbeiter : projektleiter
    Projekt "0..*" --> "1" Adresse : einsatzort
    Projekt "1..*" -- "0..*" Arbeitsauftrag : arbeitsaufträge
    Arbeitsauftrag "0..*" -- "1..*" Mitarbeiter : beteiligtePersonen
    Arbeitsauftrag "0..*" --> "1" Adresse : einsatzort
    Arbeitsauftrag "1" *-- "0..*" Unterauftrag : unteraufträge
    Termin "0..*" --> "0..1" Arbeitsauftrag : arbeitsauftrag
    Termin "0..*" --> "0..1" Projekt : projekt
    Termin "0..*" --> "0..1" Buchung : buchung
    Unterauftrag "0..*" --> "0..1" Unterauftragnehmer : auftragnehmer
    Rechnung "0..*" --> "1" Arbeitsauftrag : arbeitsauftrag
    `GerätExemplar` "0..*" --> "1" `GerätTyp` : gerätTyp
    `GerätExemplar` "1" *-- "0..*" `Ausrüstung` : ausrüstung
    `GerätExemplar` "0..*" --> "1" Lager : lager
    Lager "0..*" --> "1" Adresse : adresse
    Buchung "0..*" -- "1..*" `GerätExemplar` : gerätExemplare
    Buchung "0..*" --> "1" Arbeitsauftrag : arbeitsauftrag
    Buchung "0..*" --> "1" Mitarbeiter : gebuchtVon
    Bild "0..*" --> "1" Mitarbeiter : hochlader
    Mitarbeiter "1" *-- "0..*" Bild : bilder
    Arbeitsauftrag "1" *-- "0..*" Bild : bilder
    Projekt "1" *-- "0..*" Bild : bilder
    `GerätExemplar` "1" *-- "0..*" Bild : bilder
    Finanzbuchhaltung ..> Rechnung : liest