= Use-Case-Diagramm

Im Rahmen der in diesem Abschnitt folgenden Use-Case-Analyse wird die Funktionalität der gesamten Verwaltungsanwendung für das Bauunternehmen untersucht und verdeutlicht. Zunächst wird ein allgemeines Use-Case-Diagramm erstellt, welches die Hauptfunktionalitäten der Anwendung abbildet. Hierbei wird ein funktionsorientierter Ansatz verfolgt, sodass differenziert auf die einzelnen Funktionalitäten eingegangen werden kann. Beispielhaft wird für ausgewählte Use-Cases eine Verfeinerung vorgenommen, um die Funktionalität des Verwaltens komplexerer Entitäten näher darzustellen. Die Darstellung orientiert sich an den im Lastenheft definierten Produktfunktionen (LF10-LF100) und berücksichtigt die unterschiedlichen Benutzerrollen mit ihren jeweiligen Zugriffsrechten.

== Rollen-Erläuterung der Anwendung

Das Diagramm wird aus sieben Akteuren zusammengesetzt, von denen die meisten den Rollen in der Anwendung entsprechen, wie sie im Lastenheft (Sektion 2.3) definiert wurden. Durch die Verwendung von Vererbungsbeziehungen zwischen den Akteuren werden gemeinsame Funktionalitäten auf Basisakteuren definiert, während spezialisierte Rollen diese Funktionen erben und um weitere Fähigkeiten erweitern. Diese Modellierung ermöglicht eine klare Darstellung der Rechtehierarchie im System.

=== Benutzer

Hierbei handelt es sich um eine abstrakte Basisrolle, die Grundlage aller Akteure innerhalb der Anwendung ist. Dies ist allerdings eine fiktive Rolle, die den Anforderungen des Lastenheftes entsprechend keinem Endnutzer direkt zugewiesen wird. Diese Rolle wurde eingeführt, um die Gemeinsamkeiten der anderen Rollen durch Generalisierungen der Akteure deutlicher darzustellen. Jeder Benutzer verfügt über die grundlegende Fähigkeit, nach Daten zu suchen und die GUI für seinen Arbeitsplatz zu konfigurieren (LF10). Die Suchfunktionen sind dabei rollenbasiert eingeschränkt, sodass jeder Benutzer nur auf die für ihn relevanten Daten zugreifen kann (LF60).

=== Mitarbeiter (Bauarbeiter)

Der Mitarbeiter repräsentiert die Bauarbeiter des Unternehmens, die auf den Baustellen tätig sind. Dies umfasst sowohl gelernte als auch ungelernte Bauarbeiter und macht den größten Teil der Belegschaft aus (ca. 170 von 200 Mitarbeitern). Diese Rolle hat minimale Systemrechte und dient primär der Selbstauskunft. Jeder Mitarbeiter kann seine eigenen Anwesenheitszeiten einsehen (LF90), die über Stempelkarten automatisch erfasst werden. Zusätzlich kann er grundlegende Informationen zu seinen zugeordneten Arbeitsaufträgen abrufen, sofern diese für seine tägliche Arbeit relevant sind. Die Rolle verfügt über keine Bearbeitungsrechte und keinen Zugriff auf Verwaltungsfunktionen.

=== Vorarbeiter

Der Vorarbeiter erweitert die Funktionalitäten eines Mitarbeiters um lesenden Zugriff auf detaillierte Informationen zu seinen eigenen Arbeitsaufträgen. Er leitet Arbeitsgruppen auf Baustellen und benötigt daher umfassende Einsicht in die ihm zugeordneten Aufträge. Dies umfasst die Auftragsbezeichnung, den Einsatzort, Start-, End- und Zwischentermine, beteiligte Personen und Gruppen, zugeordnete Baumaschinen und Werkzeuge sowie die Baupläne (als PDF-Dateien) (LF30, LF40). Der Vorarbeiter kann sowohl aktuelle als auch zukünftige Arbeitsaufträge einsehen sowie vergangene abgeschlossene Aufträge. Der Zugriff erfolgt über dedizierte PCs in den Planungsräumen. Im Rahmen des späteren Tablet-Projekts ist auch ein mobiler Zugriff mit Offline-Synchronisation vorgesehen. Die Rolle verfügt über keine Schreibrechte und kann keine neuen Aufträge anlegen oder bestehende bearbeiten.

=== Bauleitung

Die Bauleitung ist ein Basisakteur für Projektleiter und Bauleiter und fasst deren gemeinsame Funktionalitäten zusammen. Diese Rolle hat Vollzugriff auf alle projektbezogenen Daten, nicht nur auf die eigenen Projekte. Dies ermöglicht flexible Projektzusammenarbeit und Vertretungsregelungen. Die Bauleitung kann Projekte und Arbeitsaufträge anlegen, bearbeiten und löschen (LF30, LF40). Sie verwaltet Unteraufträge und ordnet externe Unterauftragnehmer zu. Mitarbeiter und Gruppen werden Projekten und Aufträgen zugeordnet. Die Bauleitung bucht Baumaschinen und Werkzeuge, wobei das System die Verfügbarkeit prüft (LF50). Der Terminplaner wird zur Koordination von Projekten, Aufträgen und Ressourcen genutzt (LF40). Bilder können zu Projekten, Aufträgen und Baumaschinen hochgeladen werden (LF80), und Baupläne werden als Dateipfade verlinkt. Kostenvoranschläge aus dem Finanzbuchhaltungssystem können lesend eingesehen werden. Die Rolle erbt alle Grundfunktionen des Benutzers, insbesondere Such- und Filterfunktionen für projektbezogene Daten.

=== Projektleiter

Der Projektleiter ist ein Bauingenieur in leitender Position und erbt alle Funktionalitäten der Bauleitung. Er trägt die Gesamtverantwortung für Projekte von der Planung bis zum Abschluss. Der Projektleiter arbeitet primär von Desktop-PCs im Büro aus und koordiniert die Projekte zentral. Zusätzlich zu den geerbten Funktionen kann der Projektleiter übergreifende Projektberichte erstellen und hat erweiterte Rechte bei der Ressourcenplanung. Die Rolle unterscheidet sich von einem Bauleiter primär durch den Arbeitsort (Büro vs. Baustelle), hat aber im System identische Rechte.

=== Bauleiter

Der Bauleiter erbt ebenfalls alle Funktionalitäten der Bauleitung und ist verantwortlich für die Koordination der Arbeiten direkt auf den Baustellen. Er arbeitet sowohl vom Büro als auch von den Baustellen aus. Im Rahmen des späteren Tablet-Projekts ist vorgesehen, dass Bauleiter über Tablets mit Offline-Modus auf ausgewählte Daten zugreifen können. Die Synchronisation erfolgt bei VPN-Verbindung oder über WLAN im Büro. Auf mobilen Geräten haben Bauleiter lesenden Zugriff auf Auftragsinformationen, Baumaschinenstandorte und Baupläne sowie Schreibzugriff auf projektbezogene Daten ihrer eigenen Projekte.

=== Verwaltungsmitarbeiter

Der Verwaltungsmitarbeiter ist primär im Büro tätig (ca. 30 von 200 Mitarbeitern) und für die Datenpflege zuständig. Diese Rolle hat Leserechte auf alle Daten im System sowie Vollzugriff auf reine Verwaltungsdaten. Der Verwaltungsmitarbeiter verwaltet Mitarbeiterstammdaten, inklusive Personalien, Kontaktdaten, Vertragsdaten und Gruppenzuordnungen (LF20). Er legt Gruppen an, bearbeitet diese und ordnet Mitarbeiter zu Gruppen zu (n:m-Beziehung). Die Anwesenheitsverwaltung umfasst die Erfassung von Anwesenheitszeiten durch Import von Stempelkarten-Daten (CSV-Format), die Festlegung des Anwesenheitstyps (Anwesend, Urlaub, Krankheit, sonstige Abwesenheit) und den Export für die Lohnabrechnung (LF90). Verwaltungsmitarbeiter haben auf projektbezogene Daten (Projekte, Aufträge, Baumaschinen, Buchungen) nur Leserechte. Sie können den Terminplaner einsehen, aber keine Termine bearbeiten. Schreibzugriff auf Projekte und Aufträge haben ausschließlich die Bauleitung und der Administrator.

=== Administrator

Der Administrator ist ein Verwaltungsmitarbeiter mit erweiterten IT-Rechten und verfügt über sämtliche Rechte innerhalb der Anwendung. Der Übersicht halber wurden die Vererbungen zu den anderen Akteuren nicht explizit im Diagramm dargestellt, jedoch hat der Administrator implizit Zugriff auf alle Funktionen aller anderen Rollen. Neben der vollen Daten-Zugriffsberechtigung ist diese Rolle für Systemverwaltungs-Funktionen zuständig. Dies umfasst die Verwaltung von Benutzerkonten (anlegen, bearbeiten, löschen) und die Zuweisung von Rollen (Administrator, Verwaltungsmitarbeiter, Projekt-/Bauleiter, Vorarbeiter, Mitarbeiter). Die Rollen sind fest vordefiniert und können nicht neu konfiguriert werden. Der Administrator importiert Daten aus dem Altsystem (CSV-Format, Semikolon-separiert, UTF-8-kodiert) und exportiert Daten für Berichte oder Backups (CSV-Format). Er erstellt manuelle Backups zusätzlich zu den automatischen täglichen und wöchentlichen Sicherungen und kann Backups wiederherstellen. Die Systemkonfiguration umfasst die Bearbeitung von Konfigurationsdateien (Schriftarten, Schriftgrößen, Überschriften) und die Verwaltung systemweiter Einstellungen. Der Administrator kann neue Kategorien für Baumaschinen und Werkzeuge hinzufügen und die Duplikatsprüfung bei bewusster Mehrfachanlage überschreiben (LF100). Zudem synchronisiert er Finanzdaten aus dem Buchhaltungssystem manuell (CSV-Import). Der Administrator verwaltet auch Lager für Baumaschinen und Werkzeuge.

== Use-Case-Diagramm der gesamten Anwendung

#figure(
  image("../assets/UseCase-Bauunternehmen-Kompaktansicht.svg", width: 100%),
  caption: [Use-Case-Diagramm der gesamten Anwendung -- Kompaktansicht der Bauunternehmens-Verwaltungssoftware]
) <uc_gesamt>

In der Darstellung des Use-Case-Diagramms (@uc_gesamt) werden, der Einfachheit halber, keine Pfeilspitzen von Akteuren zu Use-Cases dargestellt, solange die Richtung nicht relevant ist. Die Assoziation zwischen Akteur und Use-Case ist durch eine einfache Linie gekennzeichnet. Wenn in dem Use-Case-Diagramm die Rede von "verwalten" ist, dann ist hiermit sowohl das Lesen als auch die Bearbeitung der erwähnten Elemente gemeint (Anlegen, Bearbeiten, Löschen). Diese Wahl ist weniger präzise, ermöglicht allerdings eine Zusammenfassung der Use-Cases, wenn eine Unterscheidung nicht notwendig ist, weil sich das Verwalten von einzelnen Funktionen nicht wesentlich unterscheidet.

Das Diagramm ist auf maximal zehn Use-Cases pro Darstellung begrenzt, um die Übersichtlichkeit zu gewährleisten. Daher werden die Hauptfunktionalitäten in diesem Diagramm dargestellt, während spezialisierte Funktionen in Verfeinerungsdiagrammen detailliert werden.

=== Erläuterung der Darstellung und Farbcodierung

Das Use-Case-Diagramm verwendet eine Farbcodierung zur besseren Übersichtlichkeit und Gruppierung der Funktionalitäten nach Zuständigkeitsbereichen:

*Hellblau (Administrator-Funktionen):* Die in hellblau dargestellten Use-Cases ("Daten übertragen", "Daten importieren", "Daten exportieren", "Backup erstellen", "Daten archivieren", "System verwalten") sind ausschließlich dem Administrator vorbehalten. Diese Funktionen umfassen systemkritische Operationen wie Datenmigration aus dem Altsystem, Import/Export von CSV-Dateien, manuelle und automatische Backups sowie die Verwaltung von Benutzerkonten und Systemkonfigurationen. Die 10-Jahres-Frist für die Datenarchivierung ergibt sich aus gesetzlichen Aufbewahrungspflichten.

*Hellgrün (Projektbezogene Funktionen):* Die grün eingefärbten Use-Cases ("Arbeitsaufträge und Projekte verwalten", "Geräte verwalten", "Buchungen verwalten", "Personal verwalten") repräsentieren die Kernfunktionalitäten der Bauleitung (Projekt- und Bauleiter). Diese Funktionen ermöglichen die vollständige Verwaltung projektbezogener Daten, von der Projektanlage über die Ressourcenzuordnung bis zur Buchung von Baumaschinen. Der zentrale Use-Case "Verwaltungsdaten bearbeiten" (großes grünes Oval mit Extension Points) zeigt, dass die Verwaltungsmitarbeiter über `<<extend>>`-Beziehungen auf spezialisierte Verwaltungsfunktionen zugreifen können. Die vier Extension Points (EP 1: Personal verwalten, EP 2: Baumaschinen und Werkzeuge verwalten, EP 3: Geräte verwalten, EP 4: Buchungen verwalten) verdeutlichen, dass Verwaltungsmitarbeiter selektiv auf bestimmte Verwaltungsfunktionen zugreifen können, jedoch mit eingeschränkten Rechten (nur Leserechte auf projektbezogene Daten).

*Hellorange (Vorarbeiter-Funktionen):* Die orange markierten Use-Cases ("Arbeitsaufträge lesen", "Terminplaner lesen", "Baumaschinen und Werkzeuge lesen") zeigen die lesenden Zugriffe des Vorarbeiters. Diese Rolle hat ausschließlich Lesezugriff auf die für ihre Arbeit relevanten Informationen. Der Vorarbeiter kann eigene Arbeitsaufträge einsehen, den Terminplaner konsultieren und Informationen zu benötigten Baumaschinen abrufen, jedoch keine Daten bearbeiten.

*Hellgrün (Mitarbeiter-Grundfunktionen):* Die grün eingefärbten Use-Cases am unteren Rand des Diagramms ("Daten suchen und filtern", "Eigene Arbeitszeiten lesen") sind dem Mitarbeiter (Bauarbeiter) zugeordnet. Diese Basisrolle hat minimale Systemrechte und kann primär eigene Daten einsehen. Die Suchfunktion ist rollenbasiert eingeschränkt.

*Gelb (Externe Systemschnittstelle):* Der gelb markierte Use-Case "Finanzdaten lesen" repräsentiert die Integration mit dem Finanzbuchhaltungssystem. Die unidirektionale Schnittstelle (Read-Only) ermöglicht das Einlesen von Rechnungen, Mahnungen und Kostenvoranschlägen. Der externe Akteur "Finanzbuchhaltungssystem" ist als Strichmännchen außerhalb der Systemgrenze dargestellt, was verdeutlicht, dass es sich um ein separates System handelt.

Die `<<include>>`-Beziehungen (gestrichelte Pfeile) zeigen, dass bestimmte Use-Cases immer gemeinsam ausgeführt werden. Beispielsweise inkludiert "Daten importieren" automatisch "Daten übertragen", und "Backup erstellen" inkludiert ebenfalls "Daten übertragen". Die `<<extend>>`-Beziehungen vom Use-Case "Verwaltungsdaten bearbeiten" zu den vier Extension Points verdeutlichen optionale Erweiterungen, die je nach Kontext aktiviert werden.

Die Notiz im linken unteren Bereich des Diagramms erklärt die Vererbungsstruktur: "Alle vorhandenen Akteure erben vom Akteur Mitarbeiter und können seine Aktionen ausführen. Zur Verdeutlichung werden die erbenden Akteure mit einem farbigen Kopf dargestellt." Diese Konvention ermöglicht eine kompakte Darstellung ohne explizite Vererbungspfeile zu jedem einzelnen Use-Case.

=== Mitarbeiter verwalten

Ermöglicht dem Verwaltungsmitarbeiter und dem Administrator das Anlegen, Bearbeiten und Löschen von Mitarbeiterstammdaten. Dies umfasst die Eingabe von Personalien (Vorname, Nachname, Geburtsdatum), Kontaktdaten (E-Mail, Telefon, Adresse) und Vertragsdaten (Position, Beschäftigungsart, Vertragsbeginn/-ende). Jeder Mitarbeiter erhält eine eindeutige Mitarbeiternummer, die automatisch vom System vergeben wird. Die Adresse wird als separate Entität modelliert und über eine Referenz zugeordnet. Die Rolle des Mitarbeiters (Verwaltungsmitarbeiter, Bau-/Projektleiter, Vorarbeiter, Mitarbeiter, Administrator) wird durch den Administrator zugewiesen. Bei der Anlage eines neuen Mitarbeiters prüft das System automatisch auf mögliche Duplikate anhand von Vorname, Nachname und Geburtsdatum (LF100). Der Administrator kann diese Warnung bei bewusster Mehrfachanlage überschreiben. Die Mitarbeiterverwaltung ist eng mit der Gruppenverwaltung verknüpft, da Mitarbeiter mehreren Gruppen zugeordnet werden können (n:m-Beziehung) (LF20).

=== Gruppen verwalten

Umfasst das Anlegen, Bearbeiten und Löschen von Gruppen sowie die Zuordnung von Mitarbeitern zu Gruppen. Die Gruppentypen (Verwaltung, Planung, Projektleitung, Bauleitung, Baugruppen) sind fest vorgegeben, konkrete Instanzen können jedoch dynamisch erstellt werden. Jede Gruppe erhält eine eindeutige Gruppennummer, einen Namen und optional einen Gruppenleiter. Ein Mitarbeiter kann mehreren Gruppen angehören, eine Gruppe kann mehrere Mitarbeiter enthalten (n:m-Beziehung). Baugruppen enthalten Arbeitsgruppen für die Baustellen und benötigen mindestens einen Baugruppenleiter. Die Verwaltung erfolgt über eine übersichtliche GUI mit Auswahllisten, die durchsuchbar und filterbar sind (LF70). Der Verwaltungsmitarbeiter und der Administrator haben Vollzugriff auf die Gruppenverwaltung, während die Bauleitung Gruppen nur lesend einsehen und Projekten/Aufträgen zuordnen kann (LF20).

=== Projekt anlegen

Der Projektleiter oder Bauleiter legt ein neues Projekt an. Dabei wird zunächst ein Projektname und eine Beschreibung eingegeben. Die Projektnummer wird automatisch vom System vergeben. Ein Projektleiter wird dem Projekt zugeordnet (Referenz auf Mitarbeiter). Der Einsatzort wird als Adresse der Baustelle eingegeben. Start- und Endtermine werden festgelegt und der Projektstatus wird auf "Geplant" gesetzt. Optional kann eine detaillierte Projektbeschreibung hinzugefügt werden. Nach erfolgreicher Anlage ist das Projekt im Terminplaner sichtbar und kann für die Erstellung von Arbeitsaufträgen verwendet werden. Das System prüft vor dem Speichern auf mögliche Duplikate (LF100). Ein Projekt kann zunächst ohne Aufträge existieren; Aufträge werden später hinzugefügt. Die Projektverwaltung ist mit der Auftragsverwaltung über eine 1:n-Beziehung verknüpft (ein Projekt kann mehrere Aufträge enthalten).

=== Arbeitsauftrag verwalten

Ermöglicht der Bauleitung das Anlegen, Bearbeiten und Löschen von Arbeitsaufträgen. Bei der Erstellung wird eine Auftragsbezeichnung und Beschreibung eingegeben. Die Auftragsnummer wird automatisch vergeben. Der Auftrag wird einem oder mehreren Projekten zugeordnet (n:m-Beziehung), da ein Auftrag über mehrere Projekte verteilt sein kann. Es werden Start-, End- und optional Zwischentermine festgelegt. Beteiligte Personen und Gruppen werden dem Auftrag zugeordnet. Der Einsatzort wird als Adresse eingegeben. Optional können Unteraufträge angelegt und Baupläne (Dateipfade zu PDF-Dateien) verlinkt werden. Der Kostenvoranschlag wird aus dem Finanzbuchhaltungssystem lesend übernommen. Der Auftragsstatus (Offen, in Bearbeitung, abgeschlossen) wird festgelegt. Nach erfolgreicher Anlage ist der Auftrag im Terminplaner sichtbar und kann für Buchungen von Baumaschinen verwendet werden. Die Verwaltungsmitarbeiter haben auf Aufträge nur Leserechte (LF30, LF40).

=== Baumaschine/Werkzeug verwalten

Umfasst das Anlegen, Bearbeiten und Löschen von Baumaschinen und Bauwerkzeugen durch die Bauleitung oder den Administrator. Beide werden über eine gemeinsame Geräteklasse verwaltet und über ein Kategorieattribut unterschieden. Bei der Anlage wird eine Bezeichnung (z.B. "Bagger CAT 320"), eine Kategorie (Bagger, LKW, Kran, Rüttler, Bohrmaschine, Schalungsteil, Zaun, Bausicherung) und ein Typ (Baumaschine oder Bauwerkzeug) eingegeben. Die Gerätenummer wird automatisch vergeben. Eine Seriennummer (Herstellerseriennummer) wird erfasst. Das Gerät wird einem Lager zugeordnet (Referenz auf Lager). Optional wird ein aktueller Standort angegeben, falls das Gerät nicht im Lager ist. Der Status (Verfügbar, gebucht, in Wartung, defekt) wird festgelegt. Anschaffungsdatum, letzter Wartungstermin und nächster Wartungstermin werden erfasst. Ausrüstung (z.B. Baggerschaufel, Kranzubehör) kann dem Gerät zugeordnet werden. Bilder können hochgeladen werden (LF80). Der Standort kann manuell aktualisiert werden, wenn das Gerät transportiert wird. Verwaltungsmitarbeiter haben auf Baumaschinen und Werkzeuge nur Leserechte (LF50).

=== Baumaschine/Werkzeug buchen

Der Projektleiter oder Bauleiter bucht eine Baumaschine oder ein Werkzeug für einen Arbeitsauftrag. Dabei wird das gewünschte Gerät ausgewählt (über Suchfunktion oder Auswahlliste). Der Zeitraum wird durch Start- und Enddatum festgelegt. Der Auftrag wird zugeordnet (Referenz auf Arbeitsauftrag). Das System prüft automatisch die Verfügbarkeit des Geräts im angegebenen Zeitraum. Bei Verfügbarkeit wird die Buchung gespeichert und erhält eine eindeutige Buchungsnummer. Der buchende Mitarbeiter und das Buchungsdatum werden automatisch erfasst. Der Buchungsstatus wird auf "Aktiv" gesetzt. Bei Nichtverfügbarkeit wird eine Fehlermeldung angezeigt. Die Buchung kann direkt beim Anlegen eines Auftrags oder später bei Bedarf erfolgen. Bestehende Buchungen können bearbeitet oder storniert werden. Die Benutzungszeiträume werden automatisch über die Buchungen ermittelt. Die Buchungsverwaltung ermöglicht die Übersicht über alle aktuellen und zukünftigen Buchungen. Verwaltungsmitarbeiter können Buchungen nur lesend einsehen. Die Verfügbarkeitssuche ist Teil der Gerätesuche (LF50).

=== Terminplaner nutzen

Ermöglicht der Bauleitung, dem Verwaltungsmitarbeiter und dem Vorarbeiter (jeweils mit unterschiedlichen Rechten) die Nutzung des Terminplaners. Die Darstellung erfolgt als Kalenderansicht mit Monats- und Wochenansicht. Alle Aufträge und Projekte werden mit ihren Terminen angezeigt (Start-, End- und Zwischentermine). Die Ansicht kann nach Datum oder Zeitraum gefiltert werden. Die Bauleitung kann Termine eintragen, verschieben und löschen (Schreibrechte). Verwaltungsmitarbeiter können den Terminplaner nur einsehen (Leserechte). Vorarbeiter sehen nur ihre eigenen Arbeitsaufträge. Ein Klick auf einen Eintrag öffnet die Detailansicht des Auftrags oder Projekts. Der Terminplaner zeigt auch die Ressourcenverfügbarkeit (Baumaschinen, Mitarbeiter) an. Die zugeordneten Baugruppen und gebuchten Baumaschinen werden pro Eintrag angezeigt. Der Terminplaner ist eng mit der Projekt- und Auftragsverwaltung verknüpft und wird automatisch aktualisiert, wenn neue Aufträge angelegt oder Termine geändert werden. Die zugewiesenen Mitarbeiter und Unteraufträge sind ebenfalls sichtbar (LF40).

=== Daten suchen

Ermöglicht allen Benutzern das Suchen nach relevanten Daten im System. Die Suchergebnisse sind rollenbasiert eingeschränkt, sodass jeder Benutzer nur auf die für ihn zugänglichen Daten zugreifen kann. Die Suche erfolgt über eine Kombination aus Textsuche (Name, Bezeichnung, Seriennummer) und Filterung nach Kategorien/Attributen (z.B. Status, Datum, Standort). Separate Suchmasken existieren für Mitarbeiter, Gruppen, Aufträge/Projekte, Baumaschinen/Werkzeuge und Lager. Alternativ kann eine zentrale Suche mit Kategorie-Auswahl verwendet werden. Die Suchergebnisse werden als Tabelle mit den wichtigsten Attributen angezeigt. Ein Klick auf einen Eintrag öffnet die Detailansicht. Die Ergebnisse können nach verschiedenen Spalten sortiert werden (aufsteigend/absteigend). Die Verfügbarkeitssuche für Baumaschinen ermöglicht die Eingabe eines Zeitraums, und das System zeigt nur verfügbare Geräte an. Die Suchfunktion ist eng mit den Auswahllisten verknüpft, die ebenfalls durchsuchbar und filterbar sind (LF60, LF70).

=== Anwesenheitszeiten verwalten

Der Administrator und der Verwaltungsmitarbeiter erfassen und verwalten Anwesenheitszeiten für alle Mitarbeiter. Die Erfassung erfolgt primär durch Import von Stempelkarten-Daten (CSV-Format, automatisch täglich). Manuelle Eingabe ist ebenfalls möglich. Jeder Eintrag umfasst den Mitarbeiter (Referenz), das Datum, Startzeit, Endzeit und den Typ (Anwesend, Urlaub, Krankheit, sonstige Abwesenheit). Optional kann eine Bemerkung hinzugefügt werden. Die Anwesenheitszeiten werden als Tabelle dargestellt, filterbar nach Tag, Woche oder Monat. Die Gesamtstunden werden automatisch berechnet. Der Export für die Lohnabrechnung erfolgt im CSV-Format. Alle Mitarbeiter können ihre eigenen Anwesenheitszeiten einsehen (Leserecht), aber nicht bearbeiten. Vorgesetzte können die Zeiten ihrer direkten Mitarbeiter einsehen. Anwesenheitsdaten unterliegen der DSGVO und dürfen nur von berechtigten Personen eingesehen werden (LF90).

=== Daten importieren/exportieren

Ermöglicht dem Administrator den Import und Export von Daten. Der Import erfolgt aus dem Altsystem oder anderen Quellen im CSV-Format (Semikolon-separiert, UTF-8-kodiert). Alle relevanten Daten können importiert werden: Mitarbeiterdaten, Auftragsdaten, Baumaschinen- und Werkzeugdaten, Gruppenzuordnungen. Das System prüft beim Import automatisch auf Duplikate (LF100) und zeigt Warnungen an. Der Administrator kann Duplikatswarnungen überschreiben. Der Export erfolgt ebenfalls im CSV-Format und dient der Erstellung von Berichten oder Backups. Einzelne Datensätze (z.B. Aufträge, Mitarbeiterlisten) können selektiv exportiert werden. Finanztechnische Daten (Gehälter, Löhne, Projektkosten) werden nicht exportiert, da sie im separaten Finanzbuchhaltungssystem verwaltet werden. Rechnungen, Mahnungen und Kostenvoranschläge werden aus dem Finanzsystem importiert (CSV-Export, unidirektional, nur lesen). Die Synchronisation erfolgt manuell durch den Administrator bei Bedarf (z.B. wöchentlich oder nach Rechnungsstellung). Eine Verschlüsselung der Exportdaten ist nicht erforderlich, da die Dateien nur intern verwendet werden.

== Verfeinerung "Baumaschine/Werkzeug verwalten"

Als Verfeinerung wurde "Baumaschine/Werkzeug verwalten" aus obigem Diagramm ausgewählt, da es sich um eine zentrale Funktionalität mit komplexen Abhängigkeiten handelt. Die Verwaltung umfasst nicht nur das Anlegen, Bearbeiten und Löschen von Geräten, sondern auch die Zuordnung zu Lagern, die Verwaltung von Ausrüstung, die Aktualisierung von Standorten und die Berücksichtigung von Wartungsterminen. Diese Funktionalität ist eng mit dem Buchungssystem und der Verfügbarkeitssuche verknüpft.

// Hier wird das Verfeinerungsdiagramm eingefügt
// #figure(image("../assets/usecase_baumaschine_verfeinerung.png"), caption: [Use-Case-Verfeinerung: Baumaschine/Werkzeug verwalten]) <uc_baumaschine_verfeinerung>

=== Baumaschine/Werkzeug anlegen

Der Projektleiter, Bauleiter oder Administrator legt ein neues Gerät an. Die Gerätenummer wird automatisch vergeben. Eine Bezeichnung (z.B. "Bagger CAT 320") und eine Kategorie (Bagger, LKW, Kran, Rüttler, Bohrmaschine, Schalungsteil, Zaun, Bausicherung) werden eingegeben. Der Typ (Baumaschine oder Bauwerkzeug) wird festgelegt. Die Seriennummer wird erfasst. Das Gerät wird einem Lager zugeordnet (Referenz auf Lager). Der Status wird auf "Verfügbar" gesetzt. Das Anschaffungsdatum wird eingegeben. Optional können der letzte Wartungstermin und der nächste Wartungstermin erfasst werden. Dieser Use-Case inkludiert die Zuordnung zu einem Lager, die Eingabe von Attributen und optional die Zuordnung von Ausrüstung sowie das Hochladen von Bildern.

=== Lager zuordnen

Wird beim Anlegen oder Bearbeiten eines Geräts automatisch inkludiert. Der Benutzer wählt ein Lager aus einer Auswahlliste aus. Die Liste zeigt alle verfügbaren Lager mit Name, Typ (Platz oder Gebäude) und Adresse an. Die Auswahlliste ist durchsuchbar und filterbar. Wenn kein passendes Lager existiert, kann direkt ein neues Lager angelegt werden. Die Lagerzuordnung ist zwingend erforderlich, da jedes Gerät einem Lager zugeordnet sein muss. Der aktuelle Standort kann zusätzlich angegeben werden, falls das Gerät vorübergehend nicht im Lager ist (z.B. auf einer Baustelle).

=== Ausrüstung zuordnen

Erweitert optional das Anlegen oder Bearbeiten eines Geräts. Ausrüstung (z.B. Baggerschaufel, Kranzubehör wie Behälter, Gewichte, Haken, Anbaugeräte) kann einem Gerät zugeordnet werden. Die Ausrüstung wird als separate Entität verwaltet und über eine Referenz mit dem Gerät verknüpft. Jede Ausrüstung hat eine eindeutige Ausrüstungsnummer, eine Bezeichnung, einen Typ, eine Angabe zur Kompatibilität (mit welchen Gerätetypen sie verwendet werden kann), ein Gewicht und einen Status (Verfügbar, zugeordnet, in Wartung, defekt). Ein Gerät kann mehrere Ausrüstungsteile haben. Die Ausrüstung kann auch unabhängig von einem Gerät existieren und bei Bedarf zugeordnet werden. Die Suche nach Baumaschinen kann nach vorhandener Ausrüstung gefiltert werden (z.B. "Bagger mit 1,5m-Schaufel").

=== Bilder hochladen

Erweitert optional das Anlegen oder Bearbeiten eines Geräts. Der Benutzer kann ein oder mehrere Bilder (JPG, PNG, GIF, optional PDF) hochladen. Jedes Bild erhält einen vom Benutzer vergebenen Titel. Die Bilder werden zentral in einem Verzeichnis gespeichert, und der Dateipfad wird in der Datenbank referenziert. Metadaten wie Hochladedatum, Hochlader (Referenz auf Mitarbeiter), Dateigröße und Format werden automatisch erfasst. Die Bilder werden in der Detailansicht als Galerie mit Thumbnails angezeigt. Ein Klick auf ein Thumbnail öffnet das Bild in voller Größe. Mehrere Objekte können auf dasselbe Bild referenzieren. Bilder können ersetzt oder gelöscht werden; eine Versionierung ist nicht erforderlich (LF80).

=== Baumaschine/Werkzeug bearbeiten

Der Projektleiter, Bauleiter oder Administrator bearbeitet ein bestehendes Gerät. Zunächst wird das Gerät über die Suchfunktion oder Auswahlliste ausgewählt. Die bestehenden Attribute werden angezeigt und können geändert werden. Dies umfasst die Bezeichnung, Kategorie, den Status, die Lager- und Standortzuordnung, Wartungstermine und die Ausrüstung. Auch Bilder können hinzugefügt oder entfernt werden. Das System prüft vor dem Speichern auf mögliche Duplikate (z.B. anhand der Seriennummer). Änderungen an der Lagerzuordnung oder am Status werden gespeichert und wirken sich auf die Verfügbarkeitssuche aus. Dieser Use-Case inkludiert das Lesen der bestehenden Daten, die Aktualisierung von Attributen und optional die Standortaktualisierung.

=== Standort aktualisieren

Erweitert optional das Bearbeiten eines Geräts. Der aktuelle Standort wird manuell aktualisiert, wenn das Gerät transportiert wird (z.B. von einem Lager zu einer Baustelle oder zurück). Dies kann entweder durch Eingabe einer Adresse oder durch Auswahl eines Lagers erfolgen. Die Standortaktualisierung ist wichtig für die Optimierung der Projektabläufe, da so das nächstgelegene verfügbare Gerät gefunden werden kann. Die Aktualisierung erfolgt manuell durch den Benutzer; eine GPS-Ortung ist nicht erforderlich. Beim Zurücktransport zum Lager wird der Standort entsprechend aktualisiert.

=== Baumaschine/Werkzeug löschen

Der Projektleiter, Bauleiter oder Administrator löscht ein Gerät aus dem System. Zunächst wird das Gerät ausgewählt. Das System prüft, ob aktive Buchungen für dieses Gerät existieren. Wenn ja, wird eine Warnung angezeigt, und das Löschen wird verhindert oder der Benutzer muss die Buchungen zuerst stornieren. Wenn keine aktiven Buchungen vorliegen, wird das Gerät gelöscht. Referenzen zu Lagern, Ausrüstung und Bildern werden aufgelöst. Bilder werden nicht automatisch aus dem Dateisystem gelöscht, falls sie von anderen Objekten referenziert werden. Abgeschlossene Buchungen (mit Status "abgeschlossen") bleiben aus Dokumentationsgründen erhalten, auch wenn das Gerät gelöscht wurde.

=== Lager verwalten

Der Administrator verwaltet die Lager für Baumaschinen und Werkzeuge. Dies umfasst das Anlegen, Bearbeiten und Löschen von Lagern. Jedes Lager erhält eine eindeutige Lagernummer, eine Bezeichnung (z.B. "Lager Nord", "Hauptlager"), einen Typ (Platz für Außengelände oder Gebäude für Lagerhalle) und eine Adresse (Referenz auf Adresse-Entität). Optional kann eine Grundstücksbezeichnung und eine Kapazität (maximale Anzahl Geräte) angegeben werden. Lager können über die Suchfunktion gefunden und nach Typ oder Adresse gefiltert werden. Bei der Geräteverwaltung werden die verfügbaren Lager in Auswahllisten angezeigt. Ein Lager kann nur gelöscht werden, wenn keine Geräte mehr zugeordnet sind.

=== Wartungstermin festlegen

Erweitert optional das Anlegen oder Bearbeiten eines Geräts. Der Benutzer gibt den letzten Wartungstermin (Datum der letzten Wartung) und den nächsten Wartungstermin (Datum der nächsten geplanten Wartung) ein. Diese Informationen dienen der Planung und Sicherstellung der Betriebsbereitschaft. Wenn ein Gerät gewartet werden muss, kann der Status auf "in Wartung" gesetzt werden, sodass es nicht für Buchungen verfügbar ist. Nach Abschluss der Wartung wird der Status wieder auf "Verfügbar" gesetzt, und die Wartungstermine werden aktualisiert. Eine automatische Erinnerung an anstehende Wartungstermine ist nicht Teil des ersten Entwicklungsauftrags, könnte aber als Erweiterung implementiert werden.

// Weitere Verfeinerungen können nach Absprache hinzugefügt werden
